name: Nodejs CI

on:
  push:
    branches:
      - main

jobs:

    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Use Node.js 18.x
          uses: actions/setup-node@v4
          with:
            node-version: '18.x'

        - name: Install dependencies
          run: npm install

        - name: Run tests
          run: npm test

        - name: build Docker image
          run: |
            docker build -t arunagri03/mynodeapp:${{ github.run_number }} .
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker push arunagri03/mynodeapp:${{ github.run_number }}
    
    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: AWS Login
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-south-1

        - name: update kubeconfig file
          run: aws eks update-kubeconfig --name my-cluster --region ap-south-1

        - name: Deploy to EKS
          run: kubectl apply -f manifest/

        - name: check the deployment status
          run: |
            kubectl rollout status deployment nodejs-deploy
            kubectl get all

        - name: rollback on failure
          if: failure()
          run: kubectl rollout undo deployment/mydeploy